
import React, { createContext, useContext, useState } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    nav_home: "Inicio",
    nav_categories: "Categorías",
    nav_publish: "Publicar",
    nav_premium: "Premium",
    nav_donate: "Donar",
    search_placeholder: "Buscar...",
    hero_featured: "Destacado",
    hero_read_now: "Leer Ahora",
    section_popular: "Populares",
    section_popular_sub: "del día",
    section_new: "Nuevos",
    section_new_sub: "capítulos",
    status_ongoing: "En curso",
    status_finished: "Finalizado",
    status_paused: "Pausado",
    btn_chapters: "Ver capítulos",
    footer_rights: "Todos los derechos reservados.",
    cat_title: "Explorar por Género",
    cat_all: "Todos",
    filter_status: "Estado",
    filter_all_status: "Todos los estados",
    // Reader
    reader_back: "VOLVER",
    reader_chapter: "Capítulo",
    reader_page: "Página",
    reader_listen: "Escuchar Capítulo",
    reader_translate: "AI Traducir",
    reader_translating: "Traduciendo...",
    reader_translation_ai: "Traducción AI",
    reader_translation_available: "Traducción disponible en panel lateral 👉",
    reader_no_translation: "No hay traducciones aún.",
    reader_no_translation_hint: "Pulsa \"AI Traducir\" para detectar y traducir el texto de esta página.",
    reader_analyzing: "Analizando texto...",
    reader_prev_chapter: "Capítulo anterior",
    reader_next_chapter: "Capítulo siguiente",
    reader_episodes: "Episodios",
    reader_playing: "Reproduciendo Capítulo",
    reader_analyzing_chapter: "Analizando Capítulo",
    reader_transcribing: "Transcribiendo texto y generando audio...",
    reader_login_title: "Inicia sesión para usar IA",
    reader_login_desc: "Las funciones de Traducción y Audio IA son exclusivas para miembros.",
    reader_login_btn: "Iniciar Sesión",
    reader_cancel: "Cancelar",
    reader_tokens_title: "¡Te has quedado sin tokens!",
    reader_tokens_desc: "Has utilizado todas tus interacciones IA gratuitas. Adquiere un plan Premium para uso ilimitado.",
    reader_tokens_btn: "Obtener Tokens",
    reader_translation_error: "Error al traducir página. Verifica la API Key o intenta de nuevo.",
    // MangaDetail
    detail_read_first: "LEER PRIMERO",
    detail_save_list: "GUARDAR EN LISTA",
    detail_read: "LEER",
    detail_views: "Vistas",
    detail_followers: "Seguidos",
    detail_chapters_tab: "Capítulos",
    detail_synopsis_tab: "Sinopsis",
    detail_no_description: "Sin descripción disponible.",
    detail_read_more: "Leer más",
    detail_read_less: "Leer menos",
    detail_chapters_count: "Capítulos",
    detail_sort: "Ordenar",
    detail_read_status: "LEÍDO",
    detail_read_action: "LEER",
    detail_more_chapters: "Ver más capítulos anteriores...",
    detail_recommendations: "Recomendaciones",
    detail_similar: "similares",
    // Home Hero
    home_hero_title: "EL HIJO MENOR DEL MAESTRO ESPADA",
    home_hero_desc: "Una historia de redención y poder absoluto. Sigue el viaje del guerrero más fuerte en su búsqueda por reclamar su derecho de nacimiento.",
    home_crowdfunding_tag: "Crowdfunding",
    home_crowdfunding_title: "APOYA A LOS CREADORES",
    home_crowdfunding_desc: "Participa en la financiación de \"Nuestro Mundo en Estéreo\" y obtén recompensas exclusivas.",
    home_ad_banner: "TRIDENT CON TU SERIE FAVORITA",
    home_ad_banner_cta: "¡PRUÉBALOS TODOS!"
  },
  en: {
    nav_home: "Home",
    nav_categories: "Categories",
    nav_publish: "Publish",
    nav_premium: "Premium",
    nav_donate: "Donate",
    search_placeholder: "Search...",
    hero_featured: "Featured",
    hero_read_now: "Read Now",
    section_popular: "Popular",
    section_popular_sub: "today",
    section_new: "New",
    section_new_sub: "chapters",
    status_ongoing: "Ongoing",
    status_finished: "Completed",
    status_paused: "Paused",
    btn_chapters: "View Chapters",
    footer_rights: "All rights reserved.",
    cat_title: "Browse by Genre",
    cat_all: "All",
    filter_status: "Status",
    filter_all_status: "All Statuses",
    // Reader
    reader_back: "BACK",
    reader_chapter: "Chapter",
    reader_page: "Page",
    reader_listen: "Listen Chapter",
    reader_translate: "AI Translate",
    reader_translating: "Translating...",
    reader_translation_ai: "AI Translation",
    reader_translation_available: "Translation available in side panel 👉",
    reader_no_translation: "No translations yet.",
    reader_no_translation_hint: "Press \"AI Translate\" to detect and translate the text on this page.",
    reader_analyzing: "Analyzing text...",
    reader_prev_chapter: "Previous chapter",
    reader_next_chapter: "Next chapter",
    reader_episodes: "Episodes",
    reader_playing: "Playing Chapter",
    reader_analyzing_chapter: "Analyzing Chapter",
    reader_transcribing: "Transcribing text and generating audio...",
    reader_login_title: "Login to use AI",
    reader_login_desc: "AI Translation and Audio features are exclusive for members.",
    reader_login_btn: "Login",
    reader_cancel: "Cancel",
    reader_tokens_title: "You ran out of tokens!",
    reader_tokens_desc: "You have used all your free AI interactions. Get a Premium plan for unlimited use.",
    reader_tokens_btn: "Get Tokens",
    reader_translation_error: "Failed to translate page. Check API Key or try again.",
    // MangaDetail
    detail_read_first: "READ FIRST",
    detail_save_list: "SAVE TO LIST",
    detail_read: "READ",
    detail_views: "Views",
    detail_followers: "Followers",
    detail_chapters_tab: "Chapters",
    detail_synopsis_tab: "Synopsis",
    detail_no_description: "No description available.",
    detail_read_more: "Read more",
    detail_read_less: "Read less",
    detail_chapters_count: "Chapters",
    detail_sort: "Sort",
    detail_read_status: "READ",
    detail_read_action: "READ",
    detail_more_chapters: "View more previous chapters...",
    detail_recommendations: "Recommendations",
    detail_similar: "similar",
    // Home Hero
    home_hero_title: "THE YOUNGEST SON OF THE SWORD MASTER",
    home_hero_desc: "A story of redemption and absolute power. Follow the journey of the strongest warrior in his quest to reclaim his birthright.",
    home_crowdfunding_tag: "Crowdfunding",
    home_crowdfunding_title: "SUPPORT THE CREATORS",
    home_crowdfunding_desc: "Participate in the funding of \"Our World in Stereo\" and get exclusive rewards.",
    home_ad_banner: "TRIDENT WITH YOUR FAVORITE SERIES",
    home_ad_banner_cta: "TRY THEM ALL!"
  },
  pt: {
    nav_home: "Início",
    nav_categories: "Categorias",
    nav_publish: "Publicar",
    nav_premium: "Premium",
    nav_donate: "Doar",
    search_placeholder: "Buscar...",
    hero_featured: "Destaque",
    hero_read_now: "Ler Agora",
    section_popular: "Populares",
    section_popular_sub: "do dia",
    section_new: "Novos",
    section_new_sub: "capítulos",
    status_ongoing: "Em andamento",
    status_finished: "Finalizado",
    status_paused: "Pausado",
    btn_chapters: "Ver capítulos",
    footer_rights: "Todos os direitos reservados.",
    cat_title: "Explorar por Gênero",
    cat_all: "Todos",
    filter_status: "Estado",
    filter_all_status: "Todos os estados",
    // Reader
    reader_back: "VOLTAR",
    reader_chapter: "Capítulo",
    reader_page: "Página",
    reader_listen: "Ouvir Capítulo",
    reader_translate: "IA Traduzir",
    reader_translating: "Traduzindo...",
    reader_translation_ai: "Tradução IA",
    reader_translation_available: "Tradução disponível no painel lateral 👉",
    reader_no_translation: "Ainda não há traduções.",
    reader_no_translation_hint: "Pressione \"IA Traduzir\" para detectar e traduzir o texto desta página.",
    reader_analyzing: "Analisando texto...",
    reader_prev_chapter: "Capítulo anterior",
    reader_next_chapter: "Próximo capítulo",
    reader_episodes: "Episódios",
    reader_playing: "Reproduzindo Capítulo",
    reader_analyzing_chapter: "Analisando Capítulo",
    reader_transcribing: "Transcrevendo texto e gerando áudio...",
    reader_login_title: "Faça login para usar IA",
    reader_login_desc: "Os recursos de Tradução e Áudio IA são exclusivos para membros.",
    reader_login_btn: "Entrar",
    reader_cancel: "Cancelar",
    reader_tokens_title: "Você ficou sem tokens!",
    reader_tokens_desc: "Você usou todas as suas interações IA gratuitas. Adquira um plano Premium para uso ilimitado.",
    reader_tokens_btn: "Obter Tokens",
    reader_translation_error: "Falha ao traduzir página. Verifique a API Key ou tente novamente.",
    // MangaDetail
    detail_read_first: "LER PRIMEIRO",
    detail_save_list: "SALVAR NA LISTA",
    detail_read: "LER",
    detail_views: "Visualizações",
    detail_followers: "Seguidores",
    detail_chapters_tab: "Capítulos",
    detail_synopsis_tab: "Sinopse",
    detail_no_description: "Sem descrição disponível.",
    detail_read_more: "Ler mais",
    detail_read_less: "Ler menos",
    detail_chapters_count: "Capítulos",
    detail_sort: "Ordenar",
    detail_read_status: "LIDO",
    detail_read_action: "LER",
    detail_more_chapters: "Ver mais capítulos anteriores...",
    detail_recommendations: "Recomendações",
    detail_similar: "similares",
    // Home Hero
    home_hero_title: "O FILHO MAIS NOVO DO MESTRE DA ESPADA",
    home_hero_desc: "Uma história de redenção e poder absoluto. Siga a jornada do guerreiro mais forte em sua busca para reivindicar seu direito de nascimento.",
    home_crowdfunding_tag: "Crowdfunding",
    home_crowdfunding_title: "APOIE OS CRIADORES",
    home_crowdfunding_desc: "Participe do financiamento de \"Nosso Mundo em Estéreo\" e obtenha recompensas exclusivas.",
    home_ad_banner: "TRIDENT COM SUA SÉRIE FAVORITA",
    home_ad_banner_cta: "EXPERIMENTE TODOS!"
  },
  fr: {
    nav_home: "Accueil",
    nav_categories: "Catégories",
    nav_publish: "Publier",
    nav_premium: "Premium",
    nav_donate: "Faire un don",
    search_placeholder: "Rechercher...",
    hero_featured: "En vedette",
    hero_read_now: "Lire maintenant",
    section_popular: "Populaire",
    section_popular_sub: "aujourd'hui",
    section_new: "Nouveaux",
    section_new_sub: "chapitres",
    status_ongoing: "En cours",
    status_finished: "Terminé",
    status_paused: "En pause",
    btn_chapters: "Voir les chapitres",
    footer_rights: "Tous droits réservés.",
    cat_title: "Parcourir par genre",
    cat_all: "Tous",
    filter_status: "Statut",
    filter_all_status: "Tous les statuts",
    // Reader
    reader_back: "RETOUR",
    reader_chapter: "Chapitre",
    reader_page: "Page",
    reader_listen: "Écouter le chapitre",
    reader_translate: "IA Traduire",
    reader_translating: "Traduction...",
    reader_translation_ai: "Traduction IA",
    reader_translation_available: "Traduction disponible dans le panneau latéral 👉",
    reader_no_translation: "Pas encore de traductions.",
    reader_no_translation_hint: "Appuyez sur \"IA Traduire\" pour détecter et traduire le texte de cette page.",
    reader_analyzing: "Analyse du texte...",
    reader_prev_chapter: "Chapitre précédent",
    reader_next_chapter: "Chapitre suivant",
    reader_episodes: "Épisodes",
    reader_playing: "Lecture du chapitre",
    reader_analyzing_chapter: "Analyse du chapitre",
    reader_transcribing: "Transcription du texte et génération audio...",
    reader_login_title: "Connectez-vous pour utiliser l'IA",
    reader_login_desc: "Les fonctions de traduction et audio IA sont réservées aux membres.",
    reader_login_btn: "Se connecter",
    reader_cancel: "Annuler",
    reader_tokens_title: "Vous n'avez plus de jetons!",
    reader_tokens_desc: "Vous avez épuisé vos interactions IA gratuites. Obtenez un plan Premium pour un usage illimité.",
    reader_tokens_btn: "Obtenir des jetons",
    reader_translation_error: "Échec de la traduction. Vérifiez la clé API ou réessayez.",
    // MangaDetail
    detail_read_first: "LIRE D'ABORD",
    detail_save_list: "SAUVEGARDER DANS LA LISTE",
    detail_read: "LIRE",
    detail_views: "Vues",
    detail_followers: "Abonnés",
    detail_chapters_tab: "Chapitres",
    detail_synopsis_tab: "Synopsis",
    detail_no_description: "Aucune description disponible.",
    detail_read_more: "Lire plus",
    detail_read_less: "Lire moins",
    detail_chapters_count: "Chapitres",
    detail_sort: "Trier",
    detail_read_status: "LU",
    detail_read_action: "LIRE",
    detail_more_chapters: "Voir plus de chapitres précédents...",
    detail_recommendations: "Recommandations",
    detail_similar: "similaires",
    // Home Hero
    home_hero_title: "LE PLUS JEUNE FILS DU MAÎTRE D'ÉPÉE",
    home_hero_desc: "Une histoire de rédemption et de pouvoir absolu. Suivez le voyage du guerrier le plus fort dans sa quête pour réclamer son droit de naissance.",
    home_crowdfunding_tag: "Financement participatif",
    home_crowdfunding_title: "SOUTENEZ LES CRÉATEURS",
    home_crowdfunding_desc: "Participez au financement de \"Notre Monde en Stéréo\" et obtenez des récompenses exclusives.",
    home_ad_banner: "TRIDENT AVEC VOTRE SÉRIE PRÉFÉRÉE",
    home_ad_banner_cta: "ESSAYEZ-LES TOUS!"
  },
  it: {
    nav_home: "Home",
    nav_categories: "Categorie",
    nav_publish: "Pubblicare",
    nav_premium: "Premium",
    nav_donate: "Donare",
    search_placeholder: "Cerca...",
    hero_featured: "In primo piano",
    hero_read_now: "Leggi ora",
    section_popular: "Popolare",
    section_popular_sub: "oggi",
    section_new: "Nuovi",
    section_new_sub: "capitoli",
    status_ongoing: "In corso",
    status_finished: "Completato",
    status_paused: "In pausa",
    btn_chapters: "Vedi capitoli",
    footer_rights: "Tutti i diritti riservati.",
    cat_title: "Sfoglia per genere",
    cat_all: "Tutti",
    filter_status: "Stato",
    filter_all_status: "Tutti gli stati",
    // Reader
    reader_back: "INDIETRO",
    reader_chapter: "Capitolo",
    reader_page: "Pagina",
    reader_listen: "Ascolta capitolo",
    reader_translate: "IA Traduci",
    reader_translating: "Traduzione...",
    reader_translation_ai: "Traduzione IA",
    reader_translation_available: "Traduzione disponibile nel pannello laterale 👉",
    reader_no_translation: "Nessuna traduzione ancora.",
    reader_no_translation_hint: "Premi \"IA Traduci\" per rilevare e tradurre il testo di questa pagina.",
    reader_analyzing: "Analisi del testo...",
    reader_prev_chapter: "Capitolo precedente",
    reader_next_chapter: "Capitolo successivo",
    reader_episodes: "Episodi",
    reader_playing: "Riproduzione capitolo",
    reader_analyzing_chapter: "Analisi del capitolo",
    reader_transcribing: "Trascrizione del testo e generazione audio...",
    reader_login_title: "Accedi per usare l'IA",
    reader_login_desc: "Le funzioni di traduzione e audio IA sono riservate ai membri.",
    reader_login_btn: "Accedi",
    reader_cancel: "Annulla",
    reader_tokens_title: "Hai esaurito i token!",
    reader_tokens_desc: "Hai esaurito tutte le interazioni IA gratuite. Ottieni un piano Premium per un uso illimitato.",
    reader_tokens_btn: "Ottieni token",
    reader_translation_error: "Traduzione fallita. Controlla la chiave API o riprova.",
    // MangaDetail
    detail_read_first: "LEGGI PRIMA",
    detail_save_list: "SALVA NELLA LISTA",
    detail_read: "LEGGI",
    detail_views: "Visualizzazioni",
    detail_followers: "Follower",
    detail_chapters_tab: "Capitoli",
    detail_synopsis_tab: "Sinossi",
    detail_no_description: "Nessuna descrizione disponibile.",
    detail_read_more: "Leggi di più",
    detail_read_less: "Leggi di meno",
    detail_chapters_count: "Capitoli",
    detail_sort: "Ordina",
    detail_read_status: "LETTO",
    detail_read_action: "LEGGI",
    detail_more_chapters: "Vedi più capitoli precedenti...",
    detail_recommendations: "Raccomandazioni",
    detail_similar: "simili",
    // Home Hero
    home_hero_title: "IL FIGLIO PIÙ GIOVANE DEL MAESTRO DI SPADA",
    home_hero_desc: "Una storia di redenzione e potere assoluto. Segui il viaggio del guerriero più forte nella sua ricerca per rivendicare il suo diritto di nascita.",
    home_crowdfunding_tag: "Crowdfunding",
    home_crowdfunding_title: "SOSTIENI I CREATORI",
    home_crowdfunding_desc: "Partecipa al finanziamento di \"Il Nostro Mondo in Stereo\" e ottieni ricompense esclusive.",
    home_ad_banner: "TRIDENT CON LA TUA SERIE PREFERITA",
    home_ad_banner_cta: "PROVALE TUTTE!"
  },
  ja: {
    nav_home: "ホーム",
    nav_categories: "カテゴリー",
    nav_publish: "投稿",
    nav_premium: "プレミアム",
    nav_donate: "寄付",
    search_placeholder: "検索...",
    hero_featured: "注目",
    hero_read_now: "今すぐ読む",
    section_popular: "人気",
    section_popular_sub: "今日",
    section_new: "新着",
    section_new_sub: "チャプター",
    status_ongoing: "連載中",
    status_finished: "完結",
    status_paused: "休載中",
    btn_chapters: "チャプターを見る",
    footer_rights: "無断複写・転載を禁じます。",
    cat_title: "ジャンル別",
    cat_all: "すべて",
    filter_status: "状態",
    filter_all_status: "すべての状態",
    // Reader
    reader_back: "戻る",
    reader_chapter: "チャプター",
    reader_page: "ページ",
    reader_listen: "チャプターを聴く",
    reader_translate: "AI翻訳",
    reader_translating: "翻訳中...",
    reader_translation_ai: "AI翻訳",
    reader_translation_available: "翻訳がサイドパネルで利用可能です 👉",
    reader_no_translation: "まだ翻訳がありません。",
    reader_no_translation_hint: "\"AI翻訳\"を押して、このページのテキストを検出・翻訳してください。",
    reader_analyzing: "テキストを分析中...",
    reader_prev_chapter: "前のチャプター",
    reader_next_chapter: "次のチャプター",
    reader_episodes: "エピソード",
    reader_playing: "チャプター再生中",
    reader_analyzing_chapter: "チャプター分析中",
    reader_transcribing: "テキスト書き起こしと音声生成中...",
    reader_login_title: "AIを使うにはログインしてください",
    reader_login_desc: "AI翻訳・音声機能はメンバー限定です。",
    reader_login_btn: "ログイン",
    reader_cancel: "キャンセル",
    reader_tokens_title: "トークンがなくなりました!",
    reader_tokens_desc: "無料のAI利用回数を使い切りました。無制限で使うにはプレミアムプランをご購入ください。",
    reader_tokens_btn: "トークンを取得",
    reader_translation_error: "翻訳に失敗しました。APIキーを確認するか、再試行してください。",
    // MangaDetail
    detail_read_first: "最初から読む",
    detail_save_list: "リストに保存",
    detail_read: "読む",
    detail_views: "閲覧数",
    detail_followers: "フォロワー",
    detail_chapters_tab: "チャプター",
    detail_synopsis_tab: "あらすじ",
    detail_no_description: "説明はありません。",
    detail_read_more: "もっと読む",
    detail_read_less: "閉じる",
    detail_chapters_count: "チャプター",
    detail_sort: "並び替え",
    detail_read_status: "既読",
    detail_read_action: "読む",
    detail_more_chapters: "以前のチャプターをもっと見る...",
    detail_recommendations: "おすすめ",
    detail_similar: "類似",
    // Home Hero
    home_hero_title: "剣聖の末息子",
    home_hero_desc: "贖罪と絶対的な力の物語。最強の戦士が生まれながらの権利を取り戻す旅を追う。",
    home_crowdfunding_tag: "クラウドファンディング",
    home_crowdfunding_title: "クリエイターを支援",
    home_crowdfunding_desc: "\"ステレオの世界\"の資金調達に参加して、限定特典を手に入れよう。",
    home_ad_banner: "お気に入りのシリーズでTRIDENT",
    home_ad_banner_cta: "全部試してみよう！"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
